- platform: template
  sensors:
    droger_state_template:
      friendly_name: 'Droger - Status'
      value_template: >-
          {%- if is_state("binary_sensor.dryer_running", "off") %}
              Schakelaar Uit
          {%  elif states('sensor.sonoff_pow_4_power') | float >= 0.1 and states('sensor.sonoff_pow_4_power') | float < 15.0 | float %}
              Standby
          {%  elif states('sensor.sonoff_pow_4_power') | float >= 15.0 and states('sensor.sonoff_pow_4_power') | float < 3600.0 | float %}
              In gebruik
          {% else %}
              Uit
          {%- endif %}
 


