alias: "Patricia is weg"
initial_state: 'on'
condition:
  condition: state
  entity_id: input_boolean.patricia_home
  state: 'on'
# Will only trigger if all are 'not_home'
trigger:
    platform: template
    value_template: "{% if (is_state('sensor.patricia_occupancy_combined','not_home')) %}true{% endif %}"
action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.patricia_home
  - service: notify.ios_ivo
    data_template:
      title: "Notificatie"
      message: "Patricia gaat weg"
