esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s
  arduino_version: dev

wifi:
  networks:
  - ssid: !secret wifi_ssid01
    password: !secret wifi_password
  - ssid: !secret wifi_ssid02
    password: !secret wifi_password
  - ssid: !secret wifi_ssid03
    password: !secret wifi_password

esp32_ble_tracker:
  scan_interval: 90s
  
binary_sensor:
  - platform: esp32_ble_tracker
    mac_address: !secret mac_miband_ivo
    name: "MIBand Ivo ${devicelocation}"
  - platform: esp32_ble_tracker
    mac_address: !secret mac_miband_patricia
    name: "MIBand Patricia ${devicelocation}"
    
# Example configuration entry
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  discovery_retain: false
  reboot_timeout: 0s
  
# Example configuration entry
font:
  - file: "comic.ttf"
    id: my_font
    size: 10
    
i2c:
  scl: GPIO22
  sda: GPIO21

time:
  - platform: sntp
    id: sntp_time

# Example configuration entry
text_sensor:
  - platform: mqtt_subscribe
    name: "Ivo"
    id: mysensor_ivo
    topic: location/ivo
    internal: true
  - platform: mqtt_subscribe
    name: "Patricia"
    id: mysensor_patricia
    topic: location/patricia
    internal: true

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.strftime(0, 0, id(my_font), "%d-%m-%Y %H:%M", id(sntp_time).now());
      it.printf(0, 20, id(my_font), "Ivo is: %s", id(mysensor_ivo).state.c_str());
      it.printf(0, 35, id(my_font), "Patricia is: %s", id(mysensor_patricia).state.c_str());

# Example configuration entry
#switch:
#  - platform: gpio
#    name: "Blue LED"
#    pin:
#      number: 2
#      inverted: yes
##  - platform: gpio
##    name: "Red LED"
##    pin:
##      number: 14
##      inverted: yes

# Enable logging
logger:
  level: NONE

# Enable Home Assistant API
api:
  password: !secret esphomepassword
  reboot_timeout: 0s

ota:
  password: !secret esphomepassword
