wifi_ssid01: NGR7800OWRT
wifi_ssid02: FWR1750ESK
wifi_ssid03: WL5120ZLDR
wifi_password: hwyrjsAB614
esphomepassword: 0182fe11B
mac_miband_ivo: D5:50:71:B5:74:39
mac_miband_patricia: EB:96:42:85:8B:09
mqtt_broker: 192.168.1.240
mqtt_username: bluepi
mqtt_password: bluepipassword
