esphome:
  name: sonoff002
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  networks:
  - ssid: 'NGR7800OWRT'
    password: 'hwyrjsAB614'
  - ssid: 'FWR1750ESK'
    password: 'hwyrjsAB614'
  - ssid: 'WL5120ZLDR'
    password: 'hwyrjsAB614'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '0182fe11B'
  reboot_timeout: 0s

ota:
  password: '0182fe11B'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "Sonoff Basic Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Sonoff Basic Green LED"
    output: basic_green_led
    id: led

sensor:
  - platform: wifi_signal
    name: "Sonoff Basic WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Sonoff Basic Uptime"

text_sensor:
  - platform: version
    name: "Sonoff Basic ESPHome Version 1.0"
